[package]
name = "derived_from_tealr_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tealr_derive = { version = "0.9.0-alpha4", features = ["embed_compiler_from_download"] }
